version: '3'
services:
  frontend:
    build: ./frontend
    container_name: jenkins_frontend
    ports:
      - "3100:3100"
    
    environment:
      - VITE_BACKEND_API_URL=http://backend:5100/api/meals
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: jenkins_backend
    ports:
      - "5100:5100"
    
    environment:
      - NODE_ENV=development
      - PORT=5100
      - MONGO_URI=mongodb+srv://alishoaib:1234@cluster0.cmgkc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: jenkins_test
    depends_on:
      - frontend
      - backend
    volumes:
      - ./reports:/app/reports
      - ./screenshots:/app/screenshots
    environment:
      - WAIT_HOSTS=frontend:3100,backend:5100
      - WAIT_TIMEOUT=300


